apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  annotations:
    apps.open-cluster-management.io/is-local-deployable: "false"
  name: demo-tradr-service
  namespace: demo-tekton
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: demo-tradr-service
    spec:
      selector:
        app: demo-tradr
      ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
