apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  labels:
    package: service
    app:  demo-tradr
    apps.open-cluster-management.io/channel: demo-tradr-channel
    apps.open-cluster-management.io/channel-type: Namespace
  annotations:
    apps.open-cluster-management.io/is-local-deployable: "false"
  name: demo-tradr-service
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: demo-tradr-service
    spec:
      selector:
        app: demo-tradr
      ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
